dependencies:
  - ipywidgets
  - IPython
  - numpy==1.12.1
  - jupyter
  - notebook
  - matplotlib==2.0.2
  - pandas=0.19.2
  - pip:
    - git+https://github.com/scikit-learn/scikit-learn.git#egg=sklearn[complete]
